export const ADD_COMMENT = "ADD_COMMENT";
export const RENDER_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const FETCH_COMMENTS_FAILED = "FETCH_COMMENTS_FAILED";

export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_FAILED = "DISHES_FAILED";
export const ADD_DISHES = "ADD_DISHES";

export const LEADERS_LOADING = "LEADERS_LOADING";
export const FETCH_LEADERS_FAILED = "FETCH_LEADERS_FAILED";
export const RENDER_LEADERS = "RENDER_LEADERS";

export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
export const FETCH_PROMOTIONS_FAILED = "FETCH_PROMOTIONS_FAILED";
export const RENDER_PROMOTIONS = "RENDER_PROMOTIONS";
